INSERT INTO InvType VALUES (-4, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (-3, 'Canc.', 'Cancelamento', '-         ', '-')
INSERT INTO InvType VALUES (-2, 'SI', 'Saldo Inicial', '-         ', '-')
INSERT INTO InvType VALUES (-1, 'Previsao', 'Previsão', '-         ', '-')
INSERT INTO InvType VALUES (13, 'NFs', 'Nota Fiscal de Saída', 'out       ', 'Receita')
INSERT INTO InvType VALUES (14, 'Dev. NFs', 'Dev. Nota Fiscal de Saída', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (15, 'Entrega', 'Entrega', 'out       ', 'Receita')
INSERT INTO InvType VALUES (16, 'Devolução', 'Devolução', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (17, 'PV', 'Pedido de Venda', 'out       ', 'Receita')
INSERT INTO InvType VALUES (18, 'NFe', 'Nota Fiscal de Entrada', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (19, 'Dev. NFe', 'Dev. Nota Fiscal de Entrada', 'out       ', 'Receita')
INSERT INTO InvType VALUES (20, 'Recebimento', 'Recebimento de mercadoria', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (21, 'Devolução', 'Devolução de mercadorias', 'out       ', 'Receita')
INSERT INTO InvType VALUES (22, 'PC', 'Pedido de Compra', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (23, 'CV', 'Cotação de Venda', 'out       ', 'Receita')
INSERT INTO InvType VALUES (24, 'CR', 'Contas a Receber', 'in        ', 'Despesa')
INSERT INTO InvType VALUES (25, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (30, 'LCM', 'Lançamento Contábil Manual', '-         ', '-')
INSERT INTO InvType VALUES (46, 'C/P', 'Contas a pagar', 'out       ', 'Receita')
INSERT INTO InvType VALUES (57, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (58, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (59, 'EM', 'Entrada de mercadoria', '-         ', '-')
INSERT INTO InvType VALUES (60, 'SM', 'Saida de mercadoria', '-         ', '-')
INSERT INTO InvType VALUES (67, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (162, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (182, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (202, '202', '202', '-         ', '-')
INSERT INTO InvType VALUES (203, '203', '204', '-         ', '-')
INSERT INTO InvType VALUES (204, '204', '204', '-         ', '-')
INSERT INTO InvType VALUES (321, '321', '321', '-         ', '-')
INSERT INTO InvType VALUES (10000071, '-', '-', '-         ', '-')
INSERT INTO InvType VALUES (310000001, '310000001', '310000001', '-         ', '-')
INSERT INTO InvType VALUES (540000006, 'CC', 'Cotação de Compra', 'in        ', 'Despesa')
INSERT INTO OModel values (-1, 'Indefinido')
INSERT INTO OModel values (0, 'Indefinido')
INSERT INTO OModel values (1, 'Modelo 1')
INSERT INTO OModel values (2, 'Modelo 1-A')
INSERT INTO OModel values (3, 'Modelo 2')
INSERT INTO OModel values (4, 'Modelo 2-A')
INSERT INTO OModel values (5, 'Modelo 4')
INSERT INTO OModel values (6, 'Modelo 6')
INSERT INTO OModel values (7, 'Modelo 7')
INSERT INTO OModel values (8, 'Modelo 8')
INSERT INTO OModel values (9, 'Modelo 10')
INSERT INTO OModel values (10, 'Modelo 11')
INSERT INTO OModel values (11, 'Modelo 13')
INSERT INTO OModel values (12, 'Modelo 14')
INSERT INTO OModel values (13, 'Modelo 15')
INSERT INTO OModel values (14, 'Modelo 16')
INSERT INTO OModel values (15, 'Modelo 17')
INSERT INTO OModel values (16, 'Modelo 18')
INSERT INTO OModel values (17, 'Modelo 20')
INSERT INTO OModel values (18, 'Modelo 21')
INSERT INTO OModel values (19, 'Modelo 22')
INSERT INTO OModel values (20, 'Modelo 25')
INSERT INTO OModel values (21, 'Serviço')
INSERT INTO OModel values (22, 'NFFS')
INSERT INTO OModel values (23, 'RPA')
INSERT INTO OModel values (24, 'CF')
INSERT INTO OModel values (25, 'NFSS')
INSERT INTO OModel values (26, 'R')
INSERT INTO OModel values (27, 'EXTR')
INSERT INTO OModel values (28, 'FAT')
INSERT INTO OModel values (29, 'Modelo 1F')
INSERT INTO OModel values (30, 'Modelo 1AF')
INSERT INTO OModel values (31, 'Modelo 4F')
INSERT INTO OModel values (32, 'Modelo 7F')
INSERT INTO OModel values (33, 'Modelo 9')
INSERT INTO OModel values (34, 'Modelo 21F')
INSERT INTO OModel values (35, 'Modelo 22F')
INSERT INTO OModel values (36, 'Modelo 24')
INSERT INTO OModel values (37, 'Outros')
INSERT INTO OModel values (38, 'Nada')
INSERT INTO OModel values (39, 'NFe')
INSERT INTO OModel values (40, 'Misto')
INSERT INTO OModel values (41, 'Saída')
INSERT INTO OModel values (42, 'Modelo 26')
INSERT INTO OModel values (43, 'Modelo 27')
INSERT INTO OModel values (44, 'Modelo CT-e')
INSERT INTO OModel values (45, 'Modelo 57')
INSERT INTO OModel values (46, 'Modelo')
INSERT INTO OAccountType VALUES (1, 'Ativo')
INSERT INTO OAccountType VALUES (2, 'Passivo')
INSERT INTO OAccountType VALUES (3, 'Receita')
INSERT INTO OAccountType VALUES (4, 'Despesa')
INSERT INTO OAccountType VALUES (5, 'Custo')
INSERT INTO OAccountType VALUES (6, 'Compensação')
INSERT INTO OAccountType VALUES (9, 'Indefinido')
