truncate table adoc
truncate table ado1
truncate table ado2
truncate table ado3
truncate table ado4
truncate table ado5
truncate table ado6
truncate table ado7
truncate table ado8
truncate table ado9
truncate table ado10
truncate table ado11
truncate table ado12
truncate table ado13
truncate table ado14
truncate table ado15
truncate table ado16
truncate table ado17
truncate table ado18
truncate table ado19
truncate table ado20
truncate table ado21
truncate table ado22

truncate table aitm
truncate table ait1
truncate table ait2
truncate table ait3
truncate table ait5
truncate table ait6
truncate table ait7
truncate table ait8
truncate table ait9
truncate table ait11
truncate table ait13

truncate table acrd
truncate table acr1
truncate table acr2
truncate table acr3
truncate table acr5
truncate table acr7