CALL OKS_TEMPLATEGLOBALTABLES();
DROP PROCEDURE OKS_TEMPLATEGLOBALTABLES;
CREATE PROCEDURE OKS_TEMPLATEGLOBALTABLES()
AS
--DECLARAR VARIAVEIS AQUI
varTabelas INT;
BEGIN
	
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'OKSGLOBALDOCMKT';
	IF :varTabelas > 0 THEN
	 DROP TABLE OKSGLOBALDOCMKT;
	END IF;
	CREATE GLOBAL TEMPORARY COLUMN TABLE OKSGLOBALDOCMKT
	(
		"Tipo DOC" VARCHAR(6) CS_STRING NOT NULL,
      "Status Docto" VARCHAR(22) CS_STRING NOT NULL,
      "Cancelada" VARCHAR(6) CS_STRING,
      "Código PN" NVARCHAR(15) CS_STRING,
      "Nome Abreviado" NVARCHAR(100) CS_STRING,
      "Nome PN" NVARCHAR(100) CS_STRING,
      "Grupo PN" SMALLINT CS_INT,
      "Nome Grupo PN" NVARCHAR(20) CS_STRING,
      "Código Município" NVARCHAR(100) CS_STRING,
      "Nome Município" NVARCHAR(100) CS_STRING,
      "UF" NVARCHAR(3) CS_STRING,
      "Região" NVARCHAR(12) CS_STRING,
      "BPLId" INT CS_INT,
      "Filial" NVARCHAR(100) CS_STRING,
      "Número SAP" INT CS_INT,
      "DocEntry" INT CS_INT,
      "Número Referência PN" NVARCHAR(100) CS_STRING NOT NULL,
      "Número Pedido Cliente" INT CS_INT NOT NULL,
      "Projeto" NVARCHAR(20) CS_STRING,
      "Flag Nota Futura" VARCHAR CS_STRING,
      "Data Lançamento" LONGDATE CS_LONGDATE,
      "Data Documento" LONGDATE CS_LONGDATE,
      "Serial" INT CS_INT,
      "SeqName" NVARCHAR(8) CS_STRING,
      "Model" NVARCHAR(20) CS_STRING,
      "Tipo de Documento" VARCHAR(7) CS_STRING NOT NULL,
      "Condição Pagamento" NVARCHAR(100) CS_STRING,
      "Número Parcelas" SMALLINT CS_INT,
      "Forma de Pagamento" NVARCHAR(15) CS_STRING NOT NULL,
      "Indicador" NVARCHAR(2) CS_STRING,
      "Nome Indicador" NVARCHAR(50) CS_STRING,
      "Incoterms" NVARCHAR(3) CS_STRING,
      "Transportadora" NVARCHAR(15) CS_STRING,
      "Nome Transportadora" NVARCHAR(100) CS_STRING,
      "Quantidade Embalagem" INT CS_INT NOT NULL,
      "Descrição Embalagem" NVARCHAR(10) CS_STRING,
      "Peso Bruto" DECIMAL(32,6) CS_FIXED,
      "Peso Líquido" DECIMAL(32,6) CS_FIXED,
      "Código Vendedor" INT CS_INT,
      "Nome Vendedor" NVARCHAR(155) CS_STRING,
      "Representante" NVARCHAR(32) CS_STRING NOT NULL,
      "Nome Representante" NVARCHAR(50) CS_STRING NOT NULL,
      "DA Não Distr Frete" DECIMAL CS_DECIMAL_FLOAT,
      "DA Não Distr Seguro" DECIMAL CS_DECIMAL_FLOAT,
      "DA Não Distr Outros" DECIMAL CS_DECIMAL_FLOAT,
      "Tipo de Envio" NVARCHAR(40) CS_STRING NOT NULL,
      "Uso Principal" NVARCHAR(20) CS_STRING,
      "Valor Adto Usado" DECIMAL(2,2) CS_FIXED NOT NULL,
      "Status Linha" VARCHAR(7) CS_STRING NOT NULL,
      "Código Item" NVARCHAR(50) CS_STRING,
      "Descrição Item" NVARCHAR(100) CS_STRING,
      "Grupo" SMALLINT CS_INT,
      "Nome Grupo" NVARCHAR(20) CS_STRING,
      "NCM" NVARCHAR(15) CS_STRING,
      "Tipo Estrutura" VARCHAR(7) CS_STRING NOT NULL,
      "Código Vendedor Linha" INT CS_INT,
      "Nome Vendedor Linha" NVARCHAR(155) CS_STRING,
      "Depósito" NVARCHAR(8) CS_STRING,
      "DepósitoED" VARCHAR CS_STRING,
      "Linha Doc" INT CS_INT,
      "Linha Ordem" INT CS_INT,
      "Data Entrega" LONGDATE CS_LONGDATE,
      "Código Utilização" INT CS_INT,
      "Nome Utilização" NVARCHAR(20) CS_STRING,
      "Código Imposto" NVARCHAR(8) CS_STRING,
      "Só Imposto" VARCHAR CS_STRING,
      "Imposto Custo" VARCHAR CS_STRING,
      "Atualiza Estoque" VARCHAR CS_STRING,
      "Gratuito" VARCHAR CS_STRING,
      "Terceiros" VARCHAR CS_STRING,
      "CFOP" NVARCHAR(6) CS_STRING,
      "CST ICMS" NVARCHAR(6) CS_STRING,
      "CST IPI" NVARCHAR(2) CS_STRING,
      "CST PIS" NVARCHAR(2) CS_STRING,
      "CST COFINS" NVARCHAR(2) CS_STRING,
      "DocEntryBase" INT CS_INT,
      "BaseLine" INT CS_INT,
      "BaseType" INT CS_INT,
      "BaseSeqCode" SMALLINT CS_INT,
      "BaseSeqName" NVARCHAR(8) CS_STRING,
      "Tipo Saída" NVARCHAR(10) CS_STRING,
      "Conta Res" NVARCHAR(210) CS_STRING,
      "Nome Conta Res" NVARCHAR(100) CS_STRING,
      "Conta CPV" NVARCHAR(210) CS_STRING,
      "Nome Conta CPV" NVARCHAR(100) CS_STRING,
      "Quantidade" DECIMAL(34,     6) CS_FIXED,
      "Quantidade Entregue" DECIMAL(34, 6) CS_FIXED,
      "UMV" NVARCHAR(100) CS_STRING,
      "ItensUMV" DECIMAL(21, 6) CS_FIXED,
      "UME" NVARCHAR(100) CS_STRING,
      "Moeda" NVARCHAR(3) CS_STRING,
      "Unitário Moeda" DECIMAL(34,6) CS_FIXED,
      "Taxa Moeda" DECIMAL(21,6) CS_FIXED,
      "Total Mercadoria Moeda" DECIMAL CS_DECIMAL_FLOAT,
      "Unitário R$" DECIMAL CS_DECIMAL_FLOAT,
      "CMV" DECIMAL CS_DECIMAL_FLOAT,
      "Total Mercadoria R$" DECIMAL CS_DECIMAL_FLOAT,
      "DA Frete" DECIMAL CS_DECIMAL_FLOAT,
      "DA Seguro" DECIMAL CS_DECIMAL_FLOAT,
      "DA Outros" DECIMAL CS_DECIMAL_FLOAT,
      "IMPOSTOS-I" DECIMAL CS_DECIMAL_FLOAT,
      "IMPOSTOS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "Faturamento Bruto" DECIMAL CS_DECIMAL_FLOAT,
      "Faturamento Líquido" DECIMAL CS_DECIMAL_FLOAT,
      "COFINS-I" DECIMAL CS_DECIMAL_FLOAT,
      "PIS-I" DECIMAL CS_DECIMAL_FLOAT,
      "ICMS-I" DECIMAL CS_DECIMAL_FLOAT,
      "ICMSDest-I" DECIMAL CS_DECIMAL_FLOAT,
      "ICMSRemet-I" DECIMAL CS_DECIMAL_FLOAT,
      "FCP-I" DECIMAL CS_DECIMAL_FLOAT,
      "ICMS-ST-I" DECIMAL CS_DECIMAL_FLOAT,
      "IPI-I" DECIMAL CS_DECIMAL_FLOAT,
      "ISS-I" DECIMAL CS_DECIMAL_FLOAT,
      "CSLL-I" DECIMAL CS_DECIMAL_FLOAT,
      "IRPJ-I" DECIMAL CS_DECIMAL_FLOAT,
      "II-I" DECIMAL CS_DECIMAL_FLOAT,
      "OUTROS IMP-I" DECIMAL CS_DECIMAL_FLOAT,
      "COFINS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "PIS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "ICMS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "ICMSDest-NI" DECIMAL CS_DECIMAL_FLOAT,
      "ICMSRemet-NI" DECIMAL CS_DECIMAL_FLOAT,
      "FCP-NI" DECIMAL CS_DECIMAL_FLOAT,
      "ICMS-ST-NI" DECIMAL CS_DECIMAL_FLOAT,
      "IPI-NI" DECIMAL CS_DECIMAL_FLOAT,
      "ISS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "CSLL-NI" DECIMAL CS_DECIMAL_FLOAT,
      "IRPJ-NI" DECIMAL CS_DECIMAL_FLOAT,
      "II-NI" DECIMAL CS_DECIMAL_FLOAT,
      "OUTROS IMP-NI" DECIMAL CS_DECIMAL_FLOAT,
      "Base COFINS" DECIMAL CS_DECIMAL_FLOAT,
      "Base PIS" DECIMAL CS_DECIMAL_FLOAT,
      "Base ICMS" DECIMAL CS_DECIMAL_FLOAT,
      "Base ICMSDest" DECIMAL CS_DECIMAL_FLOAT,
      "Base ICMSRemet" DECIMAL CS_DECIMAL_FLOAT,
      "Base FCP" DECIMAL CS_DECIMAL_FLOAT,
      "Base ICMS-ST" DECIMAL CS_DECIMAL_FLOAT,
      "Base IPI" DECIMAL CS_DECIMAL_FLOAT,
      "Base ISS" DECIMAL CS_DECIMAL_FLOAT,
      "Base CSLL" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRPJ" DECIMAL CS_DECIMAL_FLOAT,
      "Base II" DECIMAL CS_DECIMAL_FLOAT,
      "Base OUTROS IMP" DECIMAL CS_DECIMAL_FLOAT,
      "DA COFINS-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA PIS-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMS-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMSDest-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMSRemet-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA FCP-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMS-ST-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA IPI-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA ISS-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA CSLL-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA IRPJ-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA II-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA OUTROS IMP-I" DECIMAL CS_DECIMAL_FLOAT,
      "DA COFINS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA PIS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMSDest-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMSRemet-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA FCP-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA ICMS-ST-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA IPI-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA ISS-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA CSLL-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA IRPJ-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA II-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA OUTROS IMP-NI" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base COFINS" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base PIS" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base ICMS" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base ICMSDest" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base ICMSRemet" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base FCP" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base ICMS-ST" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base IPI" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base ISS" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base CSLL" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base IRPJ" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base II" DECIMAL CS_DECIMAL_FLOAT,
      "DA Base OUTROS IMP" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-ISSF" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-IRRF" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-PIS" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-COFINS" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-CSLL" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-INSS" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-10833" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-OUTROS" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-TOTAL" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-ISSF" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-IRRF" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-PIS" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-COFINS" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-CSLL" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-INSS" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-10833" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-OUTROS" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-ISSF-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-IRRF-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-PIS-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-COFINS-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-CSLL-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-INSS-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-10833-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-OUTROS-P" DECIMAL CS_DECIMAL_FLOAT,
      "IRF-TOTAL-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-ISSF-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-IRRF-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-PIS-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-COFINS-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-CSLL-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-INSS-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-10833-P" DECIMAL CS_DECIMAL_FLOAT,
      "Base IRF-OUTROS-P" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota COFINS" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota PIS" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota ICMS" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota ICMSDest" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota ICMSRemet" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota FCP" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota ICMS-ST" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota Interna ICMS-ST" INT CS_INT,
      "MVA ICMS-ST" DECIMAL CS_DECIMAL_FLOAT,
      "MVA Linha ICMS-ST" DECIMAL(21,6) CS_FIXED,
      "Alíquota IPI" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota ISS" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota CSLL" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota IRPJ" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota II" DECIMAL CS_DECIMAL_FLOAT,
      "Alíquota OUTROS IMP" DECIMAL CS_DECIMAL_FLOAT
	);
	
	
	-- CRIAÇÃO DE TABELA COC
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'COC';
	IF :varTabelas > 0 THEN
	 DROP TABLE COC;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE COC AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA COV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'COV';
	IF :varTabelas > 0 THEN
	 DROP TABLE COV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE COV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA DTC
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'DTC';
	IF :varTabelas > 0 THEN
	 DROP TABLE DTC;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE DTC AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA DTCDEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'DTCDEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE DTCDEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE DTCDEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA ENT
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'ENT';
	IF :varTabelas > 0 THEN
	 DROP TABLE ENT;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE ENT AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA ENTDEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'ENTDEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE ENTDEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE ENTDEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA NFE
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'NFE';
	IF :varTabelas > 0 THEN
	 DROP TABLE NFE;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE NFE AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA NFEDEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'NFEDEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE NFEDEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE NFEDEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA NFS
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'NFS';
	IF :varTabelas > 0 THEN
	 DROP TABLE NFS;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE NFS AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA NFSDEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'NFSDEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE NFSDEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE NFSDEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	
	-- CRIAÇÃO DE TABELA PEC
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'PEC';
	IF :varTabelas > 0 THEN
	 DROP TABLE PEC;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE PEC AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA PEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'PEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE PEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE PEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA REC
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'REC';
	IF :varTabelas > 0 THEN
	 DROP TABLE REC;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE REC AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
	
	-- CRIAÇÃO DE TABELA RECDEV
	SELECT COUNT(1) AS "varTabelas" INTO varTabelas from "SYS"."M_TEMPORARY_TABLES" WHERE "TABLE_NAME" = 'RECDEV';
	IF :varTabelas > 0 THEN
	 DROP TABLE RECDEV;
	END IF;
	CREATE GLOBAL TEMPORARY TABLE RECDEV AS
	(
		SELECT * FROM OKSGLOBALDOCMKT WHERE 1 = 0
	);
END;